org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# Minecraft / toolchain
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
# Mod
mod_id=opencomputers
mod_name=OpenComputers: Modernized
mod_license=MIT
mod_version=1.10.7
mod_group_id=li.cil.oc
# OC repack libraries
jnlua_version=20230530.0
luaj_version=20220907.1
jnlua_natives_version=20220928.1
typesafe_config_version=1.4.9
# Integration / dependency mods (common)
cc_version=1.120.2
tis3d_version=1.7.7
architectury_version=9.2.14
markdownmanual_version=1.2.7
forgeconfigapiport_version=v21.1.6-1.21.1-Fabric
sable_companion_version=1.6.0
jei_version=15.20.0.132
rei_version=12.1.785
wthit_version=8.21.1
jade_version=11.13.2
emi_version=1.1.24
rs2_version=2.0.9
