plugins {
    id 'net.neoforged.moddev.legacyforge'
    id 'java-library'
}

base {
    archivesName = mod_id + "-core-" + minecraft_version
}

legacyForge {
    mcpVersion = minecraft_version
}

configurations {
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

dependencies {
    implementation(project(':api'))
    implementation(project(':core-api'))
    implementation files(rootProject.tasks.named('relocateTypesafe'))
    implementation("li.cil.repack:OC-LuaJ:${luaj_version}")
    compileOnly("li.cil.repack:OC-JNLua:${jnlua_version}")
    compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-common-api:${cc_version}")
    compileOnly("maven.modrinth:tis3d:MC${minecraft_version}-forge-${tis3d_version}")
    compileOnly("dev.architectury:architectury-forge:${architectury_version}")
}
