plugins {
    id 'net.neoforged.moddev.legacyforge'
    id 'java-library'
}

base {
    archivesName = mod_id + "-api"
}

legacyForge {
    mcpVersion = minecraft_version
}

configurations {
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

dependencies {
    implementation files(rootProject.tasks.named('relocateTypesafe'))
}

java {
    withSourcesJar()
    withJavadocJar()
}
